-- MySQL Script generated by MySQL Workbench
-- Sat Aug 21 10:51:19 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AdmissionsManagement
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AdmissionsManagement
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `AdmissionsManagement`.`Account`
-- -----------------------------------------------------


DROP TABLE IF EXISTS `Account` ;

CREATE TABLE IF NOT EXISTS `Account` (
  `username` NVARCHAR(20) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `name` NVARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AdmissionsYear`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AdmissionsYear` ;

CREATE TABLE IF NOT EXISTS `AdmissionsYear` (
  `idAdmissionsYear` CHAR(10) NOT NULL,
  `valueAdmissionsYear` INT NOT NULL,
  PRIMARY KEY (`idAdmissionsYear`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Majors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Majors` ;

CREATE TABLE IF NOT EXISTS `Majors` (
  `idMajors` CHAR(10) NOT NULL,
  `nameMajors` NVARCHAR(50) NOT NULL,
  `descriptionMajors` NVARCHAR(500) NULL,
  `enabled` INT NOT NULL,
  PRIMARY KEY (`idMajors`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AdmissionsManagement`.`ResultExam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ResultExam` ;

CREATE TABLE IF NOT EXISTS `ResultExam` (
  `idResultExam` CHAR(10) NOT NULL,
  `nguVan` FLOAT NULL,
  `toan` FLOAT NULL,
  `ngoaiNgu` FLOAT NULL,
  `vatLy` FLOAT NULL,
  `hoaHoc` FLOAT NULL,
  `sinhHoc` FLOAT NULL,
  `lichSu` FLOAT NULL,
  `diaLy` FLOAT NULL,
  `gdcd` FLOAT NULL,
  `diemCong` FLOAT NULL,
  PRIMARY KEY (`idResultExam`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AdmissionsManagement`.`AdmissionsMajor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AdmissionsMajor` ;

CREATE TABLE IF NOT EXISTS `AdmissionsMajor` (
  `idAdmissionsYear` CHAR(10) NOT NULL,
  `idMajors` CHAR(10) NOT NULL,
  `numberOf` INT NOT NULL COMMENT 'Chỉ tiêu',
  `groups` VARCHAR(45) NOT NULL COMMENT 'tổ hợp xét tuyển',
  `condition` INT NOT NULL COMMENT 'điểm điều kiện',
  INDEX `fk_AdmissionsMajor_AdmissionsYear1_idx` (`idAdmissionsYear` ASC) ,
  INDEX `fk_AdmissionsMajor_Majors1_idx` (`idMajors` ASC) ,
  PRIMARY KEY (`idAdmissionsYear`, `idMajors`),
  CONSTRAINT `fk_AdmissionsMajor_AdmissionsYear1`
    FOREIGN KEY (`idAdmissionsYear`)
    REFERENCES `AdmissionsYear` (`idAdmissionsYear`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AdmissionsMajor_Majors1`
    FOREIGN KEY (`idMajors`)
    REFERENCES `Majors` (`idMajors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AdmissionsManagement`.`Application`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Application` ;

CREATE TABLE IF NOT EXISTS `Application` (
  `idApplication` CHAR(10) NOT NULL,
  `avatar` LONGTEXT NULL,
  `name` NVARCHAR(50) NOT NULL,
  `gender` INT NOT NULL,
  `birthday` DATE NOT NULL,
  `birthplace` VARCHAR(100) NOT NULL,
  `ethnic` VARCHAR(20) NOT NULL COMMENT 'Dân tộc',
  `Identification` VARCHAR(45) NOT NULL COMMENT 'Số CMND',
  `expiration` DATE NOT NULL COMMENT 'Ngày hết hạn',
  `phoneNumber` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `address` VARCHAR(100) NOT NULL,
  `idResultExam` CHAR(10) NOT NULL,
  `idAdmissionsYear` CHAR(10) NOT NULL,
  `idMajors` CHAR(10) NOT NULL,
  PRIMARY KEY (`idApplication`),
  INDEX `fk_Application_ResultExam1_idx` (`idResultExam` ASC) ,
  INDEX `fk_Application_AdmissionsMajor1_idx` (`idAdmissionsYear` ASC, `idMajors` ASC) ,
  CONSTRAINT `fk_Application_ResultExam1`
    FOREIGN KEY (`idResultExam`)
    REFERENCES `ResultExam` (`idResultExam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Application_AdmissionsMajor1`
    FOREIGN KEY (`idAdmissionsYear` , `idMajors`)
    REFERENCES `AdmissionsMajor` (`idAdmissionsYear` , `idMajors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
